# Generated by Django 6.0.4 on 2026-05-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagiarismchecker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeddocument',
            name='plagiarism_score',
            field=models.FloatField(default=0),
        ),
    ]
