# Generated by Django 6.0.4 on 2026-05-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagiarismchecker', '0002_storeddocument_plagiarism_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeddocument',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='storeddocument',
            old_name='plagiarism_score',
            new_name='overall_similarity_score',
        ),
        migrations.AddField(
            model_name='storeddocument',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
    ]
