# Generated by Django 6.0.4 on 2026-05-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagiarismchecker', '0003_rename_uploaded_at_storeddocument_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeddocument',
            name='plagiarism_score',
            field=models.FloatField(default=0),
        ),
    ]
